package com.hjw.qbremote.ui

import androidx.compose.foundation.lazy.LazyListScope
import com.hjw.qbremote.data.ServerBackendType
import com.hjw.qbremote.data.ServerCapabilities
import com.hjw.qbremote.data.ServerProfile
import com.hjw.qbremote.data.model.TorrentInfo
import com.hjw.qbremote.data.model.TransferInfo

internal fun LazyListScope.serverDashboardRootPageContent(
    sessionKey: String,
    selectedServerProfile: ServerProfile?,
    showContent: Boolean,
    showDashboardCardHint: Boolean,
    showDashboardSwipeHint: Boolean,
    showSkeleton: Boolean,
    showRestorePlaceholder: Boolean,
    selectedDashboardBackendType: ServerBackendType,
    serverDashboardCapabilities: ServerCapabilities,
    serverDashboardDisplay: ServerDashboardDisplayState,
    serverDashboardVersion: String,
    serverDashboardTransferInfo: TransferInfo,
    serverDashboardTorrents: List<TorrentInfo>,
    serverDashboardTorrentCount: Int,
    displayVisibleDashboardCards: List<DashboardDisplayCardItem>,
    dashboardDragGestureKey: String,
    draggingDashboardCard: DashboardDisplayCardItem?,
    settlingDashboardCard: DashboardDisplayCardItem?,
    draggingDashboardOffsetY: () -> Float,
    settlingDashboardOffsetY: () -> Float,
    draggingDashboardTargetIndex: Int,
    draggingDashboardSession: VerticalReorderSession<DashboardDisplayCardItem>?,
    revealedDashboardHideCardKey: String?,
    dashboardCardHeights: MutableMap<String, Int>,
    dashboardLockedCardHeights: Map<String, Int>,
    onRevealHideCard: (DashboardDisplayCardItem) -> Unit,
    onHideCard: (DashboardDisplayCardItem) -> Unit,
    onStartCardDrag: (DashboardDisplayCardItem) -> Unit,
    onDragCard: (DashboardDisplayCardItem, Float) -> Unit,
    onEndCardDrag: () -> Unit,
    onCancelCardDrag: () -> Unit,
    onOpenManager: () -> Unit,
    onOpenTorrentList: () -> Unit,
    onSwitchServerProfile: (String) -> Unit,
    onEditServerProfile: (String) -> Unit,
    onRequestDeleteServerProfile: (String) -> Unit,
    onDismissHomeTorrentEntryHint: () -> Unit,
    onMarkDashboardSwipeHintSeen: () -> Unit,
    onMarkDashboardCardHintSeen: () -> Unit,
    onOpenConnection: () -> Unit,
) {
    item(key = "server_dashboard_page_$sessionKey") {
        ServerDashboardPageContent(
            selectedServerProfile = selectedServerProfile,
            showContent = showContent,
            showDashboardCardHint = showDashboardCardHint,
            showDashboardSwipeHint = showDashboardSwipeHint,
            showSkeleton = showSkeleton,
            showRestorePlaceholder = showRestorePlaceholder,
            selectedDashboardBackendType = selectedDashboardBackendType,
            serverDashboardCapabilities = serverDashboardCapabilities,
            serverDashboardDisplay = serverDashboardDisplay,
            serverDashboardVersion = serverDashboardVersion,
            serverDashboardTransferInfo = serverDashboardTransferInfo,
            serverDashboardTorrents = serverDashboardTorrents,
            serverDashboardTorrentCount = serverDashboardTorrentCount,
            displayVisibleDashboardCards = displayVisibleDashboardCards,
            dashboardDragGestureKey = dashboardDragGestureKey,
            draggingDashboardCard = draggingDashboardCard,
            settlingDashboardCard = settlingDashboardCard,
            draggingDashboardOffsetY = draggingDashboardOffsetY,
            settlingDashboardOffsetY = settlingDashboardOffsetY,
            draggingDashboardTargetIndex = draggingDashboardTargetIndex,
            draggingDashboardSession = draggingDashboardSession,
            revealedDashboardHideCardKey = revealedDashboardHideCardKey,
            dashboardCardHeights = dashboardCardHeights,
            dashboardLockedCardHeights = dashboardLockedCardHeights,
            onRevealHideCard = onRevealHideCard,
            onHideCard = onHideCard,
            onStartCardDrag = onStartCardDrag,
            onDragCard = onDragCard,
            onEndCardDrag = onEndCardDrag,
            onCancelCardDrag = onCancelCardDrag,
            onOpenManager = onOpenManager,
            onOpenTorrentList = onOpenTorrentList,
            onSwitchServerProfile = onSwitchServerProfile,
            onEditServerProfile = onEditServerProfile,
            onRequestDeleteServerProfile = onRequestDeleteServerProfile,
            onDismissHomeTorrentEntryHint = onDismissHomeTorrentEntryHint,
            onMarkDashboardSwipeHintSeen = onMarkDashboardSwipeHintSeen,
            onMarkDashboardCardHintSeen = onMarkDashboardCardHintSeen,
            onOpenConnection = onOpenConnection,
        )
    }
}

